name: Project Deployment
on:
  push:
    branches:
      - master
  pull_request:
    branches: -master
  workflow_dispatch:
jobs:
  lint:
    name: Performing Project Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Execute lint command
        run: npm run lint
  build:
    needs: [lint]
    name: Performing Project Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Execute build command
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifacts@v4
        with:
          name: dist-files
          path: dist
